services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 3000
        environment:
            - NODE_ENV=production
        restart: always

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - nextjs
        restart: always
